-- H2测试表结构（与MySQL兼容）

CREATE TABLE IF NOT EXISTS short_drama_provider (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_code VARCHAR(32) NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider_code)
);

CREATE TABLE IF NOT EXISTS short_drama_connection (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    connection_name VARCHAR(64) NOT NULL,
    base_url VARCHAR(512) DEFAULT NULL,
    partner_id VARCHAR(64) DEFAULT NULL,
    api_key_ciphertext TEXT DEFAULT NULL,
    currency CHAR(3) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    filing_mode VARCHAR(16) NOT NULL DEFAULT 'API',
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider_id),
    CONSTRAINT fk_test_drama_connection_provider
        FOREIGN KEY (provider_id) REFERENCES short_drama_provider (id)
);

MERGE INTO short_drama_provider (provider_code, provider_name, status)
KEY (provider_code) VALUES ('GOODSHORT', 'GoodShort', 1);

CREATE TABLE IF NOT EXISTS provider_commission_rule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    channel_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_commission_rate DECIMAL(12, 10) NOT NULL,
    downstream_fee_rate DECIMAL(12, 10) NOT NULL,
    downstream_commission_rate DECIMAL(12, 10) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider_id),
    CONSTRAINT fk_test_provider_commission_provider
        FOREIGN KEY (provider_id) REFERENCES short_drama_provider (id)
);

CREATE TABLE IF NOT EXISTS sys_admin_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32) DEFAULT NULL,
    email VARCHAR(128) DEFAULT NULL,
    avatar_url VARCHAR(512) DEFAULT NULL,
    department_id BIGINT DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    is_super_admin TINYINT NOT NULL DEFAULT 0,
    last_login_at TIMESTAMP DEFAULT NULL,
    last_login_ip VARCHAR(64) DEFAULT NULL,
    password_changed_at TIMESTAMP DEFAULT NULL,
    remark VARCHAR(500) DEFAULT NULL,
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (username),
    UNIQUE (mobile),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS promotion_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_no CHAR(12) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(64) DEFAULT NULL,
    real_name VARCHAR(64) DEFAULT NULL,
    mobile VARCHAR(32) DEFAULT NULL,
    email VARCHAR(128) DEFAULT NULL,
    avatar_url VARCHAR(512) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    register_source VARCHAR(32) DEFAULT NULL,
    last_login_at TIMESTAMP DEFAULT NULL,
    last_login_ip VARCHAR(64) DEFAULT NULL,
    remark VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_no),
    UNIQUE (mobile),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS promotion_media_account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    external_account_id VARCHAR(128) NOT NULL,
    account_name VARCHAR(128) DEFAULT NULL,
    account_link VARCHAR(512) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    data_version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (media_type, external_account_id),
    CONSTRAINT fk_test_media_account_user
        FOREIGN KEY (user_id) REFERENCES promotion_user (id)
);

CREATE TABLE IF NOT EXISTS provider_media_filing (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    media_account_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    submitted_data_version INT DEFAULT NULL,
    task_data_version INT NOT NULL DEFAULT 1,
    remote_status VARCHAR(64) DEFAULT NULL,
    external_filing_id VARCHAR(128) DEFAULT NULL,
    filing_time TIMESTAMP DEFAULT NULL,
    operate_time TIMESTAMP DEFAULT NULL,
    operate_by BIGINT DEFAULT NULL,
    next_action VARCHAR(16) NOT NULL DEFAULT 'SUBMIT',
    next_action_at TIMESTAMP DEFAULT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    last_submitted_at TIMESTAMP DEFAULT NULL,
    last_queried_at TIMESTAMP DEFAULT NULL,
    last_error_code VARCHAR(64) DEFAULT NULL,
    last_error_message VARCHAR(512) DEFAULT NULL,
    lease_owner VARCHAR(64) DEFAULT NULL,
    lease_until TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, media_account_id),
    CONSTRAINT fk_test_filing_connection
        FOREIGN KEY (connection_id) REFERENCES short_drama_connection (id),
    CONSTRAINT fk_test_filing_media_account
        FOREIGN KEY (media_account_id) REFERENCES promotion_media_account (id)
);

CREATE TABLE IF NOT EXISTS provider_drama (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    external_drama_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    original_title VARCHAR(255),
    description CLOB,
    cover_url VARCHAR(1024),
    language VARCHAR(32) NOT NULL,
      drama_type VARCHAR(64),
      commission_scope VARCHAR(255),
      promotion_description CLOB,
      remote_show_status VARCHAR(32),
    local_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    remote_updated_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, external_drama_id),
    CONSTRAINT fk_test_drama_connection FOREIGN KEY (connection_id) REFERENCES short_drama_connection (id)
);

CREATE TABLE IF NOT EXISTS provider_drama_content (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    drama_id BIGINT NOT NULL,
    external_content_id VARCHAR(128),
    sequence_no INT NOT NULL,
    title VARCHAR(255),
    is_free TINYINT NOT NULL DEFAULT 0,
    duration_seconds INT,
    remote_updated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (drama_id, sequence_no),
    CONSTRAINT fk_test_drama_content_drama FOREIGN KEY (drama_id) REFERENCES provider_drama (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS promotion_link (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    drama_id BIGINT NOT NULL,
    media_account_id BIGINT NOT NULL,
    request_key VARCHAR(64) NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    campaign_name VARCHAR(128),
    provider_code VARCHAR(32) NOT NULL,
    external_code VARCHAR(255),
    share_url VARCHAR(2048),
    custom_params VARCHAR(255),
    landing_type VARCHAR(32) NOT NULL DEFAULT 'DEFAULT',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_error_code VARCHAR(64),
    last_error_message VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tracking_no),
    UNIQUE (user_id, request_key),
    FOREIGN KEY (user_id) REFERENCES promotion_user (id),
    FOREIGN KEY (provider_id) REFERENCES short_drama_provider (id),
    FOREIGN KEY (connection_id) REFERENCES short_drama_connection (id),
    FOREIGN KEY (drama_id) REFERENCES provider_drama (id),
    FOREIGN KEY (media_account_id) REFERENCES promotion_media_account (id)
);

CREATE TABLE IF NOT EXISTS promotion_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    drama_id BIGINT NOT NULL,
    request_key VARCHAR(64) NOT NULL,
    task_name VARCHAR(128) NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    external_code VARCHAR(255),
    direct_url VARCHAR(2048),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_error_code VARCHAR(64),
    last_error_message VARCHAR(512),
    code_search_count BIGINT NOT NULL DEFAULT 0,
    direct_click_count BIGINT NOT NULL DEFAULT 0,
    app_click_count BIGINT NOT NULL DEFAULT 0,
    lead_count BIGINT NOT NULL DEFAULT 0,
    order_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    order_count BIGINT NOT NULL DEFAULT 0,
    ad_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, request_key, media_type),
    UNIQUE (tracking_no),
    CONSTRAINT fk_test_promotion_task_user FOREIGN KEY (user_id) REFERENCES promotion_user (id),
    CONSTRAINT fk_test_promotion_task_provider FOREIGN KEY (provider_id) REFERENCES short_drama_provider (id),
    CONSTRAINT fk_test_promotion_task_connection FOREIGN KEY (connection_id) REFERENCES short_drama_connection (id),
    CONSTRAINT fk_test_promotion_task_drama FOREIGN KEY (drama_id) REFERENCES provider_drama (id)
);

CREATE TABLE IF NOT EXISTS provider_commission_rule_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    channel_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_commission_rate DECIMAL(12, 10) NOT NULL,
    downstream_fee_rate DECIMAL(12, 10) NOT NULL,
    downstream_commission_rate DECIMAL(12, 10) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (provider_id) REFERENCES short_drama_provider (id),
    FOREIGN KEY (rule_id) REFERENCES provider_commission_rule (id)
);

CREATE TABLE IF NOT EXISTS promotion_order (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    external_order_id VARCHAR(128) NOT NULL,
    external_user_id VARCHAR(128),
    external_drama_id VARCHAR(128),
    search_code VARCHAR(64),
    channel_code VARCHAR(128),
    partner_id VARCHAR(128),
    order_amount_minor BIGINT NOT NULL,
    order_amount DECIMAL(18, 2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    raw_status VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    paid_at TIMESTAMP,
    provider_updated_at TIMESTAMP,
    custom_params VARCHAR(255),
    tracking_no VARCHAR(64),
    promotion_link_id BIGINT,
    user_id BIGINT,
    media_account_id BIGINT,
    drama_id BIGINT,
    attribution_status VARCHAR(16) NOT NULL DEFAULT 'UNATTRIBUTED',
    rule_history_id BIGINT,
    channel_fee_rate DECIMAL(12, 10),
    principal_fee_rate DECIMAL(12, 10),
    principal_commission_rate DECIMAL(12, 10),
    downstream_fee_rate DECIMAL(12, 10),
    downstream_commission_rate DECIMAL(12, 10),
    commission_amount DECIMAL(18, 2),
    commission_status VARCHAR(24),
    raw_payload_json CLOB NOT NULL,
    sync_start_date TIMESTAMP NOT NULL,
    sync_end_date TIMESTAMP NOT NULL,
    first_synced_at TIMESTAMP NOT NULL,
    last_synced_at TIMESTAMP NOT NULL,
    last_error_message VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, external_order_id),
    FOREIGN KEY (connection_id) REFERENCES short_drama_connection (id),
    FOREIGN KEY (provider_id) REFERENCES short_drama_provider (id),
    FOREIGN KEY (promotion_link_id) REFERENCES promotion_link (id),
    FOREIGN KEY (user_id) REFERENCES promotion_user (id),
    FOREIGN KEY (media_account_id) REFERENCES promotion_media_account (id),
    FOREIGN KEY (drama_id) REFERENCES provider_drama (id),
    FOREIGN KEY (rule_history_id) REFERENCES provider_commission_rule_history (id)
);

CREATE TABLE IF NOT EXISTS provider_sync_checkpoint (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    sync_type VARCHAR(16) NOT NULL,
    language VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'IDLE',
    page_no INT NOT NULL DEFAULT 1,
    page_size INT NOT NULL DEFAULT 100,
    update_time BIGINT,
    last_success_at TIMESTAMP,
    requested_at TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    total_fetched INT NOT NULL DEFAULT 0,
    total_upserted INT NOT NULL DEFAULT 0,
    inserted_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64),
    last_error_message VARCHAR(512),
    lease_owner VARCHAR(64),
    lease_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, sync_type, language),
    CONSTRAINT fk_test_sync_checkpoint_connection FOREIGN KEY (connection_id) REFERENCES short_drama_connection (id)
);

CREATE TABLE IF NOT EXISTS system_scheduled_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_code VARCHAR(64) NOT NULL,
    title VARCHAR(128) NOT NULL,
    description VARCHAR(255) NOT NULL,
    cycle_type VARCHAR(32) NOT NULL DEFAULT 'INTERVAL_MINUTES',
    interval_value INT DEFAULT 60,
    interval_hours_part INT DEFAULT 0,
    interval_minutes_part INT DEFAULT 0,
    time_of_day TIME,
    day_of_week TINYINT,
    day_of_month TINYINT,
    month_of_year TINYINT,
    interval_minutes INT NOT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    next_run_at TIMESTAMP,
    lease_owner VARCHAR(64),
    lease_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (task_code),
    CHECK (interval_minutes BETWEEN 5 AND 1440)
);
