-- H2测试表结构（与MySQL兼容）

CREATE TABLE IF NOT EXISTS short_drama_provider (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_code VARCHAR(32) NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    UNIQUE (provider_code)
);

CREATE TABLE IF NOT EXISTS short_drama_connection (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    connection_name VARCHAR(64) NOT NULL,
    base_url VARCHAR(512) DEFAULT NULL,
    media_root_domain VARCHAR(253) DEFAULT NULL,
    partner_id VARCHAR(64) DEFAULT NULL,
    api_key_ciphertext TEXT DEFAULT NULL,
    currency CHAR(3) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    filing_mode VARCHAR(16) NOT NULL DEFAULT 'API',
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider_id));

MERGE INTO short_drama_provider (provider_code, provider_name, status)
KEY (provider_code) VALUES ('GOODSHORT', 'GoodShort', 1);

CREATE TABLE IF NOT EXISTS provider_commission_rule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    channel_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_commission_rate DECIMAL(12, 10) NOT NULL,
    downstream_fee_rate DECIMAL(12, 10) NOT NULL,
    downstream_commission_rate DECIMAL(12, 10) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider_id));

CREATE TABLE IF NOT EXISTS sys_admin_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32) DEFAULT NULL,
    email VARCHAR(128) DEFAULT NULL,
    avatar_url VARCHAR(512) DEFAULT NULL,
    department_id BIGINT DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    is_super_admin TINYINT NOT NULL DEFAULT 0,
    last_login_at TIMESTAMP DEFAULT NULL,
    last_login_ip VARCHAR(64) DEFAULT NULL,
    password_changed_at TIMESTAMP DEFAULT NULL,
    remark VARCHAR(500) DEFAULT NULL,
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (username),
    UNIQUE (mobile),
    UNIQUE (email),
    INDEX idx_admin_status (status)
);

CREATE TABLE IF NOT EXISTS promotion_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_no CHAR(12) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(64) DEFAULT NULL,
    real_name VARCHAR(64) DEFAULT NULL,
    mobile VARCHAR(32) DEFAULT NULL,
    email VARCHAR(128) DEFAULT NULL,
    avatar_url VARCHAR(512) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    register_source VARCHAR(32) DEFAULT NULL,
    last_login_at TIMESTAMP DEFAULT NULL,
    last_login_ip VARCHAR(64) DEFAULT NULL,
    remark VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_no),
    UNIQUE (mobile),
    UNIQUE (email),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS system_sms_config (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    access_key_id_ciphertext VARCHAR(1024) NOT NULL,
    access_key_secret_ciphertext VARCHAR(1024) NOT NULL,
    sign_name VARCHAR(64) NOT NULL,
    register_template_code VARCHAR(64) NOT NULL,
    login_template_code VARCHAR(64) NOT NULL,
    reset_password_template_code VARCHAR(64) NOT NULL,
    smtp_host VARCHAR(255), smtp_port INT, smtp_username VARCHAR(255),
    smtp_password_ciphertext VARCHAR(1024), smtp_from_address VARCHAR(255),
    email_enabled TINYINT NOT NULL DEFAULT 0,
    enabled TINYINT NOT NULL DEFAULT 0 CHECK (enabled >= 0 AND enabled <= 1),
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS promotion_media_account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    external_account_id VARCHAR(128) NOT NULL,
    account_name VARCHAR(128) DEFAULT NULL,
    account_link VARCHAR(512) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    data_version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (media_type, external_account_id),
    INDEX idx_media_account_user_status (user_id, status));

CREATE TABLE IF NOT EXISTS provider_media_filing (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    media_account_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    submitted_data_version INT DEFAULT NULL,
    task_data_version INT NOT NULL DEFAULT 1,
    remote_status VARCHAR(64) DEFAULT NULL,
    external_filing_id VARCHAR(128) DEFAULT NULL,
    filing_time TIMESTAMP DEFAULT NULL,
    operate_time TIMESTAMP DEFAULT NULL,
    operate_by BIGINT DEFAULT NULL,
    next_action VARCHAR(16) NOT NULL DEFAULT 'SUBMIT',
    next_action_at TIMESTAMP DEFAULT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    last_submitted_at TIMESTAMP DEFAULT NULL,
    last_queried_at TIMESTAMP DEFAULT NULL,
    last_error_code VARCHAR(64) DEFAULT NULL,
    last_error_message VARCHAR(512) DEFAULT NULL,
    lease_owner VARCHAR(64) DEFAULT NULL,
    lease_until TIMESTAMP DEFAULT NULL,
    UNIQUE (connection_id, media_account_id),
    INDEX idx_filing_due_task (next_action, next_action_at),
    INDEX idx_filing_media_account (media_account_id));

CREATE TABLE IF NOT EXISTS provider_drama (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    external_drama_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    original_title VARCHAR(255),
    title_zh VARCHAR(255),
    description CLOB,
    cover_url VARCHAR(1024),
    label_names CLOB,
    category_name VARCHAR(255),
    language VARCHAR(32) NOT NULL,
      remote_rank INT,
      drama_type VARCHAR(64),
      novel_type VARCHAR(32),
      novel_sub_type INT,
      commission_scope VARCHAR(255),
      promotion_description CLOB,
      remote_show_status VARCHAR(32),
    local_status VARCHAR(16) NOT NULL DEFAULT 'PUBLISHED',
    remote_created_at TIMESTAMP,
    remote_updated_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, external_drama_id),
    INDEX idx_provider_drama_query (connection_id, language, local_status));

CREATE TABLE IF NOT EXISTS provider_drama_content (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    drama_id BIGINT NOT NULL,
    external_content_id VARCHAR(128),
    sequence_no INT NOT NULL,
    title VARCHAR(255),
    is_free TINYINT NOT NULL DEFAULT 0,
    duration_seconds INT,
    content_url CLOB,
    remote_updated_at TIMESTAMP,
    UNIQUE (drama_id, sequence_no));

CREATE TABLE IF NOT EXISTS provider_drama_content_sync_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    drama_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'REQUESTED',
    requested_at TIMESTAMP NOT NULL,
    next_run_at TIMESTAMP NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    total_fetched INT NOT NULL DEFAULT 0,
    inserted_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64),
    last_error_message VARCHAR(512),
    lease_owner VARCHAR(64),
    lease_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (drama_id),
    INDEX idx_drama_content_sync_task_due (status, next_run_at, lease_until));

CREATE TABLE IF NOT EXISTS drama_sync_display_run (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    parent_run_id VARCHAR(36),
    sync_domain VARCHAR(16) NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    trigger_source VARCHAR(16) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_drama_sync_display_run_query (provider_id, sync_domain, requested_at)
);

CREATE TABLE IF NOT EXISTS drama_sync_display_run_item (
    run_id VARCHAR(36) NOT NULL,
    task_domain VARCHAR(16) NOT NULL,
    task_id BIGINT NOT NULL,
    PRIMARY KEY (run_id, task_domain, task_id),
    INDEX idx_drama_sync_display_run_item_task (task_domain, task_id)
);

CREATE TABLE IF NOT EXISTS promotion_link (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    drama_id BIGINT NOT NULL,
    batch_no VARCHAR(64) NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    link_variant VARCHAR(16) NOT NULL,
    request_key VARCHAR(64) NOT NULL,
    tracking_no VARCHAR(64) NOT NULL,
    campaign_name VARCHAR(128),
    external_code VARCHAR(255),
    share_url VARCHAR(2048),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_error_code VARCHAR(64),
    last_error_message VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tracking_no),
    UNIQUE (user_id, request_key, media_type, link_variant),
    INDEX idx_promotion_link_user_created (user_id, created_at),
    INDEX idx_promotion_link_batch (user_id, batch_no));



CREATE TABLE IF NOT EXISTS provider_commission_rule_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    channel_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_fee_rate DECIMAL(12, 10) NOT NULL,
    principal_commission_rate DECIMAL(12, 10) NOT NULL,
    downstream_fee_rate DECIMAL(12, 10) NOT NULL,
    downstream_commission_rate DECIMAL(12, 10) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_commission_rule_history_provider (provider_id, id));

CREATE TABLE IF NOT EXISTS promotion_order (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    external_order_id VARCHAR(128) NOT NULL,
    external_user_id VARCHAR(128),
    external_drama_id VARCHAR(128),
    search_code VARCHAR(64),
    channel_code VARCHAR(128),
    partner_id VARCHAR(128),
    order_amount_minor BIGINT NOT NULL,
    order_amount DECIMAL(18, 2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    raw_status VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status REGEXP '^(UNPAID|PAID|REFUNDED|UNKNOWN)$'),
    paid_at TIMESTAMP,
    provider_updated_at TIMESTAMP,
    custom_params VARCHAR(255),
    tracking_no VARCHAR(64),
    promotion_link_id BIGINT,
    user_id BIGINT,
    drama_id BIGINT,
    attribution_status VARCHAR(16) NOT NULL DEFAULT 'UNATTRIBUTED',
    rule_history_id BIGINT,
    channel_fee_rate DECIMAL(12, 10),
    principal_fee_rate DECIMAL(12, 10),
    principal_commission_rate DECIMAL(12, 10),
    downstream_fee_rate DECIMAL(12, 10),
    downstream_commission_rate DECIMAL(12, 10),
    commission_amount DECIMAL(18, 2),
    commission_status VARCHAR(24),
    raw_payload_json CLOB NOT NULL,
    sync_start_date TIMESTAMP NOT NULL,
    sync_end_date TIMESTAMP NOT NULL,
    last_synced_at TIMESTAMP NOT NULL,
    last_error_message VARCHAR(512),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, external_order_id),
    INDEX idx_promotion_order_user_paid (user_id, paid_at),
    INDEX idx_promotion_order_attribution (attribution_status, paid_at));

CREATE TABLE IF NOT EXISTS provider_sync_checkpoint (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    sync_type VARCHAR(16) NOT NULL,
    language VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'IDLE',
    page_no INT NOT NULL DEFAULT 1,
    page_size INT NOT NULL DEFAULT 100,
    update_time BIGINT,
    last_success_at TIMESTAMP,
    requested_at TIMESTAMP,
    total_fetched INT NOT NULL DEFAULT 0,
    inserted_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64),
    last_error_message VARCHAR(512),
    lease_owner VARCHAR(64),
    lease_until TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (connection_id, sync_type, language),
    INDEX idx_provider_sync_due (status, requested_at, lease_until));

CREATE TABLE IF NOT EXISTS system_scheduled_task (
    task_code VARCHAR(64) NOT NULL PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    cycle_type VARCHAR(32) NOT NULL DEFAULT 'INTERVAL_MINUTES',
    interval_value INT DEFAULT NULL,
    interval_hours_part INT DEFAULT 0,
    interval_minutes_part INT DEFAULT 0,
    time_of_day TIME,
    day_of_week TINYINT,
    day_of_month TINYINT,
    month_of_year TINYINT,
    enabled TINYINT NOT NULL DEFAULT 1,
    next_run_at TIMESTAMP,
    lease_owner VARCHAR(64),
    lease_until TIMESTAMP,
    INDEX idx_system_scheduled_task_due (enabled, next_run_at, lease_until)
);

CREATE TABLE IF NOT EXISTS promotion_analytical_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    report_date DATE NOT NULL,
    pid VARCHAR(128) NOT NULL,
    custom_params VARCHAR(255) NOT NULL DEFAULT '',
    book_id VARCHAR(128) NOT NULL DEFAULT '',
    code VARCHAR(128) NOT NULL DEFAULT '',
    click_count BIGINT NOT NULL,
    attributed_user_count BIGINT NOT NULL,
    new_registered_user_count BIGINT NOT NULL,
    new_paid_user_count BIGINT NOT NULL,
    new_member_user_count BIGINT NOT NULL,
    paid_user_count BIGINT NOT NULL,
    order_count BIGINT NOT NULL,
    order_amount DECIMAL(18,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (report_date, pid, custom_params, book_id, code)
);
