CREATE TABLE `promotion_link` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL COMMENT '推广用户内部 ID',
    `provider_id` BIGINT NOT NULL COMMENT '短剧平台 ID',
    `connection_id` BIGINT NOT NULL COMMENT '平台接入账号 ID',
    `drama_id` BIGINT NOT NULL COMMENT '本地短剧 ID',
    `media_account_id` BIGINT NOT NULL COMMENT '推广用户媒体账号 ID',
    `request_key` VARCHAR(64) NOT NULL COMMENT '用户请求幂等键',
    `tracking_no` VARCHAR(64) NOT NULL COMMENT '本地推广追踪号',
    `campaign_name` VARCHAR(128) DEFAULT NULL COMMENT '推广名称',
    `provider_code` VARCHAR(32) NOT NULL COMMENT '平台编码快照',
    `external_code` VARCHAR(255) DEFAULT NULL COMMENT '平台推广口令或编码',
    `share_url` VARCHAR(2048) DEFAULT NULL COMMENT '平台分享链接',
    `custom_params` VARCHAR(255) DEFAULT NULL COMMENT '平台回传自定义参数',
    `landing_type` VARCHAR(32) NOT NULL DEFAULT 'DEFAULT' COMMENT '落地页类型',
    `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING生成中 SUCCESS成功 FAILED失败',
    `last_error_code` VARCHAR(64) DEFAULT NULL COMMENT '最近错误码',
    `last_error_message` VARCHAR(512) DEFAULT NULL COMMENT '最近错误摘要',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_promotion_link_tracking_no` (`tracking_no`),
    UNIQUE KEY `uk_promotion_link_user_request` (`user_id`, `request_key`),
    KEY `idx_promotion_link_user_created` (`user_id`, `created_at`),
    CONSTRAINT `fk_promotion_link_user` FOREIGN KEY (`user_id`) REFERENCES `promotion_user` (`id`),
    CONSTRAINT `fk_promotion_link_provider` FOREIGN KEY (`provider_id`) REFERENCES `short_drama_provider` (`id`),
    CONSTRAINT `fk_promotion_link_connection` FOREIGN KEY (`connection_id`) REFERENCES `short_drama_connection` (`id`),
    CONSTRAINT `fk_promotion_link_drama` FOREIGN KEY (`drama_id`) REFERENCES `provider_drama` (`id`),
    CONSTRAINT `fk_promotion_link_media_account` FOREIGN KEY (`media_account_id`) REFERENCES `promotion_media_account` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推广用户生成的推广链接';
