CREATE TABLE `promotion_task` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `provider_id` BIGINT UNSIGNED NOT NULL,
    `connection_id` BIGINT UNSIGNED NOT NULL,
    `drama_id` BIGINT UNSIGNED NOT NULL,
    `request_key` VARCHAR(64) NOT NULL,
    `task_name` VARCHAR(128) NOT NULL,
    `media_type` VARCHAR(32) NOT NULL,
    `tracking_no` VARCHAR(64) NOT NULL,
    `external_code` VARCHAR(255) DEFAULT NULL,
    `direct_url` VARCHAR(2048) DEFAULT NULL,
    `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    `last_error_code` VARCHAR(64) DEFAULT NULL,
    `last_error_message` VARCHAR(512) DEFAULT NULL,
    `code_search_count` BIGINT NOT NULL DEFAULT 0,
    `direct_click_count` BIGINT NOT NULL DEFAULT 0,
    `app_click_count` BIGINT NOT NULL DEFAULT 0,
    `lead_count` BIGINT NOT NULL DEFAULT 0,
    `order_amount` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `order_count` BIGINT NOT NULL DEFAULT 0,
    `ad_amount` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_promotion_task_request_media` (`user_id`,`request_key`,`media_type`),
    UNIQUE KEY `uk_promotion_task_tracking_no` (`tracking_no`),
    KEY `idx_promotion_task_user_created` (`user_id`,`created_at`),
    CONSTRAINT `fk_promotion_task_user` FOREIGN KEY (`user_id`) REFERENCES `promotion_user` (`id`),
    CONSTRAINT `fk_promotion_task_provider` FOREIGN KEY (`provider_id`) REFERENCES `short_drama_provider` (`id`),
    CONSTRAINT `fk_promotion_task_connection` FOREIGN KEY (`connection_id`) REFERENCES `short_drama_connection` (`id`),
    CONSTRAINT `fk_promotion_task_drama` FOREIGN KEY (`drama_id`) REFERENCES `provider_drama` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推广任务';
